### ISSUE TITLE
Hey men i have a problem

### ISSUE THREAD

**Issue by ElPresidentePro** [MinecraftB0ss/Annihilation#4]
Cannot Build the porm.xml.

How can build?

**Comment by PlayFriik** [comment]
Just remove that, it's not needed...

**Comment by ElPresidentePro** [comment]
i delete and?? i have other errors "Wrapper", i use netbeans or i use eclipse?

**Comment by ElPresidentePro** [comment]
@PlayFriik  what it is ? http://gyazo.com/975f43438f970a7aae121a6aefdab97e

**Comment by ElPresidentePro** [comment]
import org.mcstats.Metrics not exist??

**Comment by PlayFriik** [comment]
Remove Metrics from this plugin too, it's outdated.

**Comment by ElPresidentePro** [comment]
@PlayFriik  ok good but i dont have errors but start compiling have error pls i need help -i use netbeans

**Comment by ElPresidentePro** [comment]
@PlayFriik my skype : osmanygon
